### ISSUE TITLE
Purpose of "./external"

### ISSUE THREAD

**Issue by kirubakaran** [AmanoTeam/Unalix#1]
Hi @SnwMds,

Thank you for making this library. I'm considering using this in my project, but I see that `./external` has some code that fetches external files. However, I don't see this used anywhere. Can you please clarify?

Thanks!

**Comment by SnwMds** [comment]
These tools are used to fetch and update some external files required by Unalix. Both are indeed for manual usage.

- `update_ca_bundle.py`
  - This script downloads a bundle of CA certificates that are used for validating HTTPS connections. You can see this file being declared [here](https://github.com/AmanoTeam/Unalix/blob/0d133f102c066d8e3886b93a5d2d12920db81d41/unalix/config/paths.py#L20) and used [here](https://github.com/AmanoTeam/Unalix/blob/0d133f102c066d8e3886b93a5d2d12920db81d41/unalix/core/ssl_context.py#L7).

- `update_rules_file.py`
  - This script downloads the regex ruleset used in the ClearURLs extension. You can see this file being declared [here](https://github.com/AmanoTeam/Unalix/blob/0d133f102c066d8e3886b93a5d2d12920db81d41/unalix/config/paths.py#L8) and used [here](https://github.com/AmanoTeam/Unalix/blob/0d133f102c066d8e3886b93a5d2d12920db81d41/unalix/core/url_cleaner.py#L11).

CA bundle: [ca-bundle.crt](https://github.com/AmanoTeam/Unalix/blob/master/unalix/package_data/ca/ca-bundle.crt)  
Ruleset: [data.min.json](https://github.com/AmanoTeam/Unalix/blob/master/unalix/package_data/rulesets/data.min.json)

**Comment by kirubakaran** [comment]
Thanks @SnwMds
