### ISSUE TITLE
file not found `package_directory`

### ISSUE THREAD

**Issue by banagale** [AmanoTeam/Unalix#2]
Thanks for your work on this package.

I went to upgrade to `.8` just now and had the package throw an exception around a missing ruleset expected in `package_directory`.

The exception occurs as part of the `import unalix`.

It looks like perhaps the pypi package is missing the `package_directory` since it is in .7 and .6. Reverting, those both operate as expected for me.

I had a look at the code diff from .7 to .8 and did not see where this might have fallen off. 

Here's the traceback:

```
< django startup stuff>
  File "/code/app/briefings/views.py", line 3, in <module>
    import unalix
  File "/code/.virtualenvs/app/lib/python3.9/site-packages/unalix/__init__.py", line 29, in <module>
    from .core.url_cleaner import clear_url
  File "/code/.virtualenvs/app/lib/python3.9/site-packages/unalix/core/url_cleaner.py", line 11, in <module>
    rulesets = coreutils.rulesets_from_files(
  File "/code/.virtualenvs/app/lib/python3.9/site-packages/unalix/core/coreutils.py", line 15, in rulesets_from_files
    with open(file=ruleset, mode="r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/code/.virtualenvs/app/lib/python3.9/site-packages/unalix/package_data/rulesets/data.min.json'
```

**Comment by SnwMds** [comment]
I did some research and it seems to be due the new behavior introduced in [PEP 517 package builder following version 0.5.0 and higher](https://github.com/pypa/build/commit/3507f2d3cac6d998136cff3c6deb09548862ecfc).

Previous versions relies on `wheel` to generate binary distributions, but now it uses `sdist` by default, which somehow does not seems to be compatible with Unalix.

I have not noticed this before. Sorry about that.

I just released a new version with the fix. Can you check?

**Comment by banagale** [comment]
@SnwMds Tested `0.8.1`, seems just fine. Thank you for the quick fix.

Looks like 517 has a lot of discussion behind it, [including follow-ups PEP 660 and 662](https://discuss.python.org/t/pep-660-editable-installs-for-pep-517-style-build-backends/8510).

This was discussed  on the [most recent episode of Test and Code](https://testandcode.com/163) in an interview with Stéphane Bidoul. I didn't have much context until now! Anyhow, you might enjoy hearing more about this change there.
